<p style="font-family: Arial; font-size:3.75vw;color:purple; font-style:bold"><br>
numpy Exercise Notebook:
</p><br>

# Exercise Notebook Instructions

### 1. Important: Only modify the cells which instruct you to modify them - leave "do not modify" cells alone.  

The code which tests your responses assumes you have run the startup/read-only code exactly.

### 2. Work through the notebook in order.

Some of the steps depend on previous, so you'll want to move through the notebook in order.

### 3. It is okay to use libraries.

You may find some questions are fairly straightforward to answer using built-in library functions.  That's totally okay - part of the point of these exercises is to familiarize you with the commonly used functions.

### 4. Seek help if stuck

If you get stuck, don't worry!  You can either review the videos/notebooks from this week, ask in the course forums, or look to the solutions for the correct answer.  BUT, be careful about looking to the solutions too quickly.  Struggling to get the right answer is an important part of the learning process.

In [1]:
# DO NOT MODIFY

# import appropriate libraries
import numpy as np

In [109]:
# DO NOT MODIFY

# we will use this dummy matrix for some portions of this exercise.

def get_matrix():
    return np.array(
      [[ 0.35066314,  0.94844269,  0.69324339,  0.32790416],
       [ 0.7935923 ,  0.9212632 ,  0.13607887,  0.56358399],
       [ 0.25597054,  0.74834666,  0.81322464,  0.11280075],
       [ 0.53822742,  0.63970183,  0.1439784 ,  0.58045905]])

mat = get_matrix()
print(type(mat))

<class 'numpy.ndarray'>


<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 1: Create a slice<br><br></p>


In the cell below, modify the function to RETURN elements occuring in the first two rows and 2nd-3rd columns

In [3]:
# modify this cell

def find_slice(matx):
    ### BEGIN SOLUTION
        return matx[:2, 1:3]
    ### END SOLUTION

In [22]:
# DO NOT MODIFY
ans = [[ 0.94844269,  0.69324339],[ 0.9212632 ,  0.13607887]]

try: 
    assert np.alltrue(find_slice(mat) == np.array(ans))
    print('Well done, you are right!')
except AssertionError as e: print("Try again, your output did not match the expected answer above")

Well done, you are right!


<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 2: Update portion of numpy array<br><br></p>


In the cell below, modify the function to perform in-place addition of 1000 to every element of slice you just created 
and RETURN the changed version

In [46]:
# modify this cell

def update_slice(matx):
    ### BEGIN SOLUTION
        matx[:2, 1:3] += 1000
        return matx
    ### END SOLUTION

In [47]:
# DO NOT MODIFY

ans = [[ 1000.94844269,  1000.69324339],[ 1000.9212632 ,  1000.13607887]]

try: 
    mat=get_matrix()
    update_slice(mat)
    assert np.alltrue(find_slice(mat) == np.array(ans))
    print('Well done, you are right!')
except AssertionError as e: print("Try again: be sure to check both your update_slice and find_slide functions.")

Well done, you are right!


<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 3: Boolean Indexing<br><br></p>

In the cell below, modify the function to RETURN elements of matrix that are < 1.5

In [89]:
# modify this cell

def boolean_filter(matx):
    ### BEGIN SOLUTION
# first create the boolean matrix as t
    t = matx[:, :] < 1.5
# then index the original matrix by the boolean matrix to return matrix equal to ans below with all elements < 1.5
    return matx[t]
    ### END SOLUTION
    
# alteratively: simply return matx[matx<1.5]

In [90]:
# DO NOT MODIFY

ans = [ 0.35066314,  0.32790416,  0.7935923 ,  0.56358399,  0.25597054,
        0.74834666,  0.81322464,  0.11280075,  0.53822742,  0.63970183,
        0.1439784 ,  0.58045905]

try:
    assert np.alltrue(boolean_filter(mat) == np.array(ans))
    print('You are right!')
except AssertionError as e: print("Try again, your solution did not produce the expected output above")

You are right!


<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 4: Convert to integer data type<br><br></p>

In the cell below, modify the function to convert each element of entered matrix to np.int data type
AND return a new matrix with converted data type (i.e. full of integers)

In [93]:
# modify this cell

def int_converter(matx):
    ### BEGIN SOLUTION
    return np.array(matx, dtype=np.int64)
    ### END SOLUTION

In [94]:
# DO NOT MODIFY

ans = [[   0, 1000, 1000,    0],
       [   0, 1000, 1000,    0],
       [   0,    0,    0,    0],
       [   0,    0,    0,    0]]

try:
    assert np.alltrue(int_converter(mat) == np.array(ans))
    print('Well done, you got it')
except AssertionError as e: print("Try again - be sure your code from Exercise 2 worked properly as well.")

Well done, you got it


<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 5: Advanced Filtering<br><br></p>

In the cell below, modify the function to perform inplace update of input matrix such that
each element that is even is replaced with number 55. <br> Note that the function does not return anything but changes the matri inplace.

In [101]:
# modify this cell

def selective_replace(matx):
    ### BEGIN SOLUTION
# simply index by the rule and update the values accordingly. indexing by matx to start with iterates through all elements
    matx[matx % 2 == 0] = 55
    ### END SOLUTION

In [102]:
# DO NOT MODIFY
test = np.array([[ 22,  3.69324339],[ 10.9212632 ,  34]])
resp = np.array([[ 55., 3.69324339],[ 10.9212632,   55.]])

try: 
    selective_replace(test)
    print(test)
    assert np.alltrue(test == resp)
except AssertionError as e: print("Try again, your function did not produce the expected output above.")

[[55.          3.69324339]
 [10.9212632  55.        ]]


<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 6: Create a slice<br><br></p>


In the cell below, modify the function to take the input matrix and RETURN mean of each row.
For example: if input matrix is 4rowsx2columns, it should return a 4 element array containing means of each row

In [110]:
# modify this cell

def row_means(matx):
    ### BEGIN SOLUTION
# axis 1 is for rows, axis 0 is for columns.
# stats operations can be used as methods on ndarray objects once they are defined
    return matx.mean(axis = 1)
    ### END SOLUTION

In [111]:
# DO NOT MODIFY
test = np.array([[ 22.33,  4.53, 10.64],[ 10.23 ,  34.56, 100.97]])
ans  = np.array([ 12.5, 48.58666667])

try: 
    print(row_means(test))
    assert np.allclose(row_means(test) , ans)
    print('Well done!')
except AssertionError as e: print("Try again - the output was not the means of each row.")

[12.5        48.58666667]
Well done!


<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 7: Detect unique members of input matrix
<br><br></p>


In the cell below, modify the function to RETURN unique elements of numpy array sent as input

In [121]:
# modify this cell

def unique_finder(matx):
    ### BEGIN SOLUTION
    return np.unique(matx)
    ### END SOLUTION

In [122]:
# DO NOT MODIFY

test = np.array([[ 22.33,  4.53, 10.64],[ 10.64 ,  4.53, 100.97]])
ans  = np.array([   4.53,   10.64,   22.33,  100.97])

try:
    assert np.allclose(unique_finder(test) , ans)
    print('Nice one mate')
except AssertionError as e: print("Try again")

Nice one mate


<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 8: Broadcasting - <br><br>add first row to every row of the input matrix<br><br></p>


In the cell below, modify the function to RETURN a new matrix by taking first row
of the input matrix and adding it to every row of entered matrix.

So if the input matrix is:<br>
2, 3<br>
1, 4

The output should be:<br>
4, 6<br>
3, 7

See how the first row (2,3) was added to itself and all subsequent rows.

In [129]:
# modify this cell

def first_row_adder(matx):
    ### BEGIN SOLUTION
    return matx + matx[0,:]
    ### END SOLUTION

In [130]:
# DO NOT MODIFY
test = np.array([[ 22.33,  4.53, 10.64],[ 10.64 ,  4.53, 100.97]])
ans = [[  44.66,    9.06,   21.28], [  32.97,    9.06,  111.61]]

try:
    assert np.allclose(first_row_adder(test), np.array(ans))
    print(first_row_adder(test))
    print('Nice one mate, well done. Grab a beer')
except AssertionError as e: print("Try again, first row was not added to all other rows")

[[ 44.66   9.06  21.28]
 [ 32.97   9.06 111.61]]
Nice one mate, well done. Grab a beer
